# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:

    runs-on: ubuntu-latest
    env:
      node-version: 16.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js $node-version
        uses: actions/setup-node@v3
        with:
          node-version: $node-version
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Zip artifacts
        run: zip release.zip ./dist/* -r

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: './dist/*.zip'

